// Copyright (c) 2017 Vadim Macagon
// MIT License, see LICENSE file for full terms.

import Dexie from 'dexie';

export interface IRepositoryRecord {
  /** Unique id (generated by the database). */
  id?: number;
  /** The root directory of the repository. */
  localPath: string;
  /** Name to use when displaying the repository in the UI. */
  name: string;
}

/**
 * IndexedDB-backed local database used to persist application state.
 */
export class AppDatabase extends Dexie {
  repositoryTable: Dexie.Table<IRepositoryRecord, number>;

  constructor(name: string) {
    super(name);

    this.version(1).stores({
      repositoryTable: '++id, &localPath'
    });
  }
}
